## jobs represent one-off tasks that run to completion and then stop.
# Their purpose is to reliably execute batch workloads, such as data processing or running a script, by ensuring that a specified number of pods successfully complete their tasks
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
