apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-already-created-disk-1
spec:
  capacity:
    storage: 1Gi # Specify the exact size of your EBS volume
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  awsElasticBlockStore:
    volumeID: vol-06f6c687ebe0be57c
    fsType: ext4

---
# creating pvc from an existing pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-already-created-disk-1
  storageClassName: null

